# Generated by Django 5.0.3 on 2024-04-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_language_profile_fecharegistro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fecharegistro',
        ),
    ]
