# Generated by Django 5.0.3 on 2024-04-19 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_valoracion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
